version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Qwiri/GYF"

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["backend/Dockerfile"]

[[analyzers]]
name = "javascript"
enabled = true
