name: "📦🦑 Deploy Latest Backend to GHCR"

on:
  push:
    branches:
    - main
    - develop
    paths:
    - 'backend/**'
  workflow_dispatch:

jobs:
  github:
    name: "📦🦑 Deploy Latest Backend to GHCR"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push to staging GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/qwiri/gyf-backend:staging

      - if: steps.extract_branch.outputs.branch == 'main'
        name: Push to prod GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/qwiri/gyf-backend:prod

      - name: Restart staged Backend
        run: curl http://backend.staging.gyf.d2a.io:9830/BACKEND_STAGED/${{ secrets.STAGED_DEPLOY_SECRET }}

      - if: steps.extract_branch.outputs.branch == 'main'
        name: Restart deployed Backend
        run: curl http://backend.prod.gyf.d2a.io:9830/BACKEND_PROD/${{ secrets.PROD_DEPLOY_SECRET }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
