name: "📦🦑 Deploy Latest Backend to GHCR"

on:
  push:
    branches:
    - main
    - develop
    paths:
    - 'backend/**'
  workflow_dispatch:

jobs:
  github:
    name: "📦🦑 Deploy Latest Backend to GHCR"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Vars
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=commit::$(git rev-parse --short HEAD)"

      - run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}" 
          echo "Commit: ${{ steps.vars.outputs.commit }}" 

      - name: Push to staging GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/qwiri/gyf-backend:staging
          build-args: |
            "gitbranch=${{ steps.vars.outputs.branch }}"
            "gitcommit=${{ steps.vars.outputs.commit }}"

      - if: steps.vars.outputs.branch == 'main'
        name: Push to prod GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/qwiri/gyf-backend:prod
          build-args: |
            "gitbranch=${{ steps.vars.outputs.branch }}"
            "gitcommit=${{ steps.vars.outputs.commit }}"

      - name: Restart staged Backend
        uses: darmiel/yadwh-action@v1
        with:
          url: 'http://backend.staging.gyf.d2a.io:9830'
          name: 'BACKEND_STAGED'
          secret: ${{ secrets.STAGED_DEPLOY_SECRET }}
          
      - name: Restart staged Backend
        if: steps.vars.outputs.branch == 'main'
        uses: darmiel/yadwh-action@v1
        with:
          url: 'http://backend.staging.gyf.d2a.io:9830'
          name: 'BACKEND_PROD'
          secret: ${{ secrets.PROD_DEPLOY_SECRET }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
