name: "📦🦑 Deploy Released Backend to GHCR"

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  github:
    name: "📦🦑 Deploy Released Backend to GHCR"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract commit
        shell: bash
        run: echo "##[set-output name=branch;]$(echo $(git rev-parse --short HEAD))"
        id: extract_commit

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Release to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/qwiri/gyf-backend:${{ github.ref_name }}
          build-args:
            git-branch: ${{ steps.extract_branch.output.branch }}
            git-commit: ${{ steps.extract_commit.output.commit }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
